org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# API Key de Google Maps (se inyecta en el AndroidManifest).
# Cambia este valor o definelo en local.properties.
MAPS_API_KEY=YOUR_MAPS_API_KEY

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
